# Generated by Django 6.0.3 on 2026-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tasks',
            field=models.TextField(blank=True),
        ),
    ]
